### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by simoneaonzo** [caoqianli/apk-parser#37]
java.lang.StackOverflowError: null
	at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:310) ~[na:1.8.0_91]
	at net.dongliu.apk.parser.utils.Buffers.readUShort(Buffers.java:24) ~[apk-parser-2.1.2.jar:na]
	at net.dongliu.apk.parser.struct.resource.Type.readResourceEntry(Type.java:48) ~[apk-parser-2.1.2.jar:na]
	at net.dongliu.apk.parser.struct.resource.Type.getResourceEntry(Type.java:41) ~[apk-parser-2.1.2.jar:na]

I use the 2.1.2 version, and I've no problem with a lot of apks. 
With the attached file a StackOverflowError occurs. 
I did a test with apktool and it extract the manifest, so I think that the manifest is well formed.

BE CAREFUL, IT'S A MALWARE!!!
[ba4a6db3479cfd84dcf47236a0613763.apk](https://dl.dropboxusercontent.com/u/35859278/ba4a6db3479cfd84dcf47236a0613763.apk)

**Comment by caoqianli** [comment]
It seems that this apk have one resource entry cyclic reference to its self.
The new version 2.1.3 can handle it now.
