### ISSUE TITLE
NumberFormatException: For input string: "0x20000"

### ISSUE THREAD

**Issue by micrk** [caoqianli/apk-parser#38]
This happens to me in some known APKs, such as Amazon and Tripit (attached).
When trying to parse the meta using ApkParser, apkParser.getApkMeta() fails with this error:

*Exception in thread "main" java.lang.NumberFormatException: For input string: "0x20000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at net.dongliu.apk.parser.struct.xml.Attributes.getInt(Attributes.java:40)
	at net.dongliu.apk.parser.parser.ApkMetaTranslator.onStartTag(ApkMetaTranslator.java:56)
	at net.dongliu.apk.parser.parser.CompositeXmlStreamer.onStartTag(CompositeXmlStreamer.java:19)
	at net.dongliu.apk.parser.parser.BinaryXmlParser.readXmlNodeStartTag(BinaryXmlParser.java:189)
	at net.dongliu.apk.parser.parser.BinaryXmlParser.parse(BinaryXmlParser.java:101)
	at net.dongliu.apk.parser.AbstractApkParser.transBinaryXml(AbstractApkParser.java:164)
	at net.dongliu.apk.parser.AbstractApkParser.parseManifestXml(AbstractApkParser.java:123)
	at net.dongliu.apk.parser.AbstractApkParser.parseApkMeta(AbstractApkParser.java:105)
	at net.dongliu.apk.parser.AbstractApkParser.getApkMeta(AbstractApkParser.java:56)*

The problem is within ApkMetaTranslator: 
`Integer gl = attributes.getInt("glEsVersion");`
But in this case glEsVersion is 0x20000.

[TripIt-Travel-Organizer-PRO-4.1.0_www.zip](https://github.com/caoqianli/apk-parser/files/346303/TripIt-Travel-Organizer-PRO-4.1.0_www.zip)

**Comment by caoqianli** [comment]
The latest version, 2.1.3, has fixed this bug.

**Comment by micrk** [comment]
Thanks, but 2.1.3 is not available via maven.

**Comment by caoqianli** [comment]
Version 2.1.3 in maven central repo works well, you can get the jar file by link: https://repo1.maven.org/maven2/net/dongliu/apk-parser/2.1.3/apk-parser-2.1.3.jar .
Should be something wrong with you build tool or IDE.
