### ISSUE TITLE
Unexpected chunk Type:203 

### ISSUE THREAD

**Issue by pirate-code** [caoqianli/apk-parser#40]

**Comment by caoqianli** [comment]
Would you please provide full exception stack trace, and the sample apk file?

**Comment by wenyuan-wj** [comment]
I got the same error. The APK is compiled in Android 5.1 environment, the exception stack traces are:

net.dongliu.apk.parser.exception.ParserException: Unexpected chunk Type:203
	at net.dongliu.apk.parser.parser.ResourceTableParser.readChunkHeader(ResourceTableParser.java:206)
	at net.dongliu.apk.parser.parser.ResourceTableParser.readPackage(ResourceTableParser.java:92)
	at net.dongliu.apk.parser.parser.ResourceTableParser.parse(ResourceTableParser.java:59)
	at net.dongliu.apk.parser.ApkParser.parseResourceTable(ApkParser.java:300)
	at net.dongliu.apk.parser.ApkParser.transBinaryXml(ApkParser.java:201)
	at net.dongliu.apk.parser.ApkParser.parseManifestXml(ApkParser.java:150)
	at net.dongliu.apk.parser.ApkParser.parseApkMeta(ApkParser.java:137)
	at net.dongliu.apk.parser.ApkParser.getApkMeta(ApkParser.java:77)

**Comment by caoqianli** [comment]
Fixed in version 2.1.4, see https://github.com/caoqianli/apk-parser/commit/a2a0bef5cf72e50672e71acf85fd5ee602fcf340

**Comment by pirate-code** [comment]
Runing is ok, thanks
